package cl.valpoSystems.bpmTraking.orm.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class BpmInstanciaHistoricaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bpm_instancia_historica
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bpm_instancia_historica
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bpm_instancia_historica
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bpm_instancia_historica
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public BpmInstanciaHistoricaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bpm_instancia_historica
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bpm_instancia_historica
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bpm_instancia_historica
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bpm_instancia_historica
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bpm_instancia_historica
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bpm_instancia_historica
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bpm_instancia_historica
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bpm_instancia_historica
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bpm_instancia_historica
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bpm_instancia_historica
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bpm_instancia_historica
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdregIsNull() {
            addCriterion("idreg is null");
            return (Criteria) this;
        }

        public Criteria andIdregIsNotNull() {
            addCriterion("idreg is not null");
            return (Criteria) this;
        }

        public Criteria andIdregEqualTo(Long value) {
            addCriterion("idreg =", value, "idreg");
            return (Criteria) this;
        }

        public Criteria andIdregNotEqualTo(Long value) {
            addCriterion("idreg <>", value, "idreg");
            return (Criteria) this;
        }

        public Criteria andIdregGreaterThan(Long value) {
            addCriterion("idreg >", value, "idreg");
            return (Criteria) this;
        }

        public Criteria andIdregGreaterThanOrEqualTo(Long value) {
            addCriterion("idreg >=", value, "idreg");
            return (Criteria) this;
        }

        public Criteria andIdregLessThan(Long value) {
            addCriterion("idreg <", value, "idreg");
            return (Criteria) this;
        }

        public Criteria andIdregLessThanOrEqualTo(Long value) {
            addCriterion("idreg <=", value, "idreg");
            return (Criteria) this;
        }

        public Criteria andIdregIn(List<Long> values) {
            addCriterion("idreg in", values, "idreg");
            return (Criteria) this;
        }

        public Criteria andIdregNotIn(List<Long> values) {
            addCriterion("idreg not in", values, "idreg");
            return (Criteria) this;
        }

        public Criteria andIdregBetween(Long value1, Long value2) {
            addCriterion("idreg between", value1, value2, "idreg");
            return (Criteria) this;
        }

        public Criteria andIdregNotBetween(Long value1, Long value2) {
            addCriterion("idreg not between", value1, value2, "idreg");
            return (Criteria) this;
        }

        public Criteria andIdInstanciaIsNull() {
            addCriterion("id_instancia is null");
            return (Criteria) this;
        }

        public Criteria andIdInstanciaIsNotNull() {
            addCriterion("id_instancia is not null");
            return (Criteria) this;
        }

        public Criteria andIdInstanciaEqualTo(String value) {
            addCriterion("id_instancia =", value, "idInstancia");
            return (Criteria) this;
        }

        public Criteria andIdInstanciaNotEqualTo(String value) {
            addCriterion("id_instancia <>", value, "idInstancia");
            return (Criteria) this;
        }

        public Criteria andIdInstanciaGreaterThan(String value) {
            addCriterion("id_instancia >", value, "idInstancia");
            return (Criteria) this;
        }

        public Criteria andIdInstanciaGreaterThanOrEqualTo(String value) {
            addCriterion("id_instancia >=", value, "idInstancia");
            return (Criteria) this;
        }

        public Criteria andIdInstanciaLessThan(String value) {
            addCriterion("id_instancia <", value, "idInstancia");
            return (Criteria) this;
        }

        public Criteria andIdInstanciaLessThanOrEqualTo(String value) {
            addCriterion("id_instancia <=", value, "idInstancia");
            return (Criteria) this;
        }

        public Criteria andIdInstanciaLike(String value) {
            addCriterion("id_instancia like", value, "idInstancia");
            return (Criteria) this;
        }

        public Criteria andIdInstanciaNotLike(String value) {
            addCriterion("id_instancia not like", value, "idInstancia");
            return (Criteria) this;
        }

        public Criteria andIdInstanciaIn(List<String> values) {
            addCriterion("id_instancia in", values, "idInstancia");
            return (Criteria) this;
        }

        public Criteria andIdInstanciaNotIn(List<String> values) {
            addCriterion("id_instancia not in", values, "idInstancia");
            return (Criteria) this;
        }

        public Criteria andIdInstanciaBetween(String value1, String value2) {
            addCriterion("id_instancia between", value1, value2, "idInstancia");
            return (Criteria) this;
        }

        public Criteria andIdInstanciaNotBetween(String value1, String value2) {
            addCriterion("id_instancia not between", value1, value2, "idInstancia");
            return (Criteria) this;
        }

        public Criteria andIdProcesoIsNull() {
            addCriterion("id_proceso is null");
            return (Criteria) this;
        }

        public Criteria andIdProcesoIsNotNull() {
            addCriterion("id_proceso is not null");
            return (Criteria) this;
        }

        public Criteria andIdProcesoEqualTo(String value) {
            addCriterion("id_proceso =", value, "idProceso");
            return (Criteria) this;
        }

        public Criteria andIdProcesoNotEqualTo(String value) {
            addCriterion("id_proceso <>", value, "idProceso");
            return (Criteria) this;
        }

        public Criteria andIdProcesoGreaterThan(String value) {
            addCriterion("id_proceso >", value, "idProceso");
            return (Criteria) this;
        }

        public Criteria andIdProcesoGreaterThanOrEqualTo(String value) {
            addCriterion("id_proceso >=", value, "idProceso");
            return (Criteria) this;
        }

        public Criteria andIdProcesoLessThan(String value) {
            addCriterion("id_proceso <", value, "idProceso");
            return (Criteria) this;
        }

        public Criteria andIdProcesoLessThanOrEqualTo(String value) {
            addCriterion("id_proceso <=", value, "idProceso");
            return (Criteria) this;
        }

        public Criteria andIdProcesoLike(String value) {
            addCriterion("id_proceso like", value, "idProceso");
            return (Criteria) this;
        }

        public Criteria andIdProcesoNotLike(String value) {
            addCriterion("id_proceso not like", value, "idProceso");
            return (Criteria) this;
        }

        public Criteria andIdProcesoIn(List<String> values) {
            addCriterion("id_proceso in", values, "idProceso");
            return (Criteria) this;
        }

        public Criteria andIdProcesoNotIn(List<String> values) {
            addCriterion("id_proceso not in", values, "idProceso");
            return (Criteria) this;
        }

        public Criteria andIdProcesoBetween(String value1, String value2) {
            addCriterion("id_proceso between", value1, value2, "idProceso");
            return (Criteria) this;
        }

        public Criteria andIdProcesoNotBetween(String value1, String value2) {
            addCriterion("id_proceso not between", value1, value2, "idProceso");
            return (Criteria) this;
        }

        public Criteria andIdSolicitudIsNull() {
            addCriterion("id_solicitud is null");
            return (Criteria) this;
        }

        public Criteria andIdSolicitudIsNotNull() {
            addCriterion("id_solicitud is not null");
            return (Criteria) this;
        }

        public Criteria andIdSolicitudEqualTo(String value) {
            addCriterion("id_solicitud =", value, "idSolicitud");
            return (Criteria) this;
        }

        public Criteria andIdSolicitudNotEqualTo(String value) {
            addCriterion("id_solicitud <>", value, "idSolicitud");
            return (Criteria) this;
        }

        public Criteria andIdSolicitudGreaterThan(String value) {
            addCriterion("id_solicitud >", value, "idSolicitud");
            return (Criteria) this;
        }

        public Criteria andIdSolicitudGreaterThanOrEqualTo(String value) {
            addCriterion("id_solicitud >=", value, "idSolicitud");
            return (Criteria) this;
        }

        public Criteria andIdSolicitudLessThan(String value) {
            addCriterion("id_solicitud <", value, "idSolicitud");
            return (Criteria) this;
        }

        public Criteria andIdSolicitudLessThanOrEqualTo(String value) {
            addCriterion("id_solicitud <=", value, "idSolicitud");
            return (Criteria) this;
        }

        public Criteria andIdSolicitudLike(String value) {
            addCriterion("id_solicitud like", value, "idSolicitud");
            return (Criteria) this;
        }

        public Criteria andIdSolicitudNotLike(String value) {
            addCriterion("id_solicitud not like", value, "idSolicitud");
            return (Criteria) this;
        }

        public Criteria andIdSolicitudIn(List<String> values) {
            addCriterion("id_solicitud in", values, "idSolicitud");
            return (Criteria) this;
        }

        public Criteria andIdSolicitudNotIn(List<String> values) {
            addCriterion("id_solicitud not in", values, "idSolicitud");
            return (Criteria) this;
        }

        public Criteria andIdSolicitudBetween(String value1, String value2) {
            addCriterion("id_solicitud between", value1, value2, "idSolicitud");
            return (Criteria) this;
        }

        public Criteria andIdSolicitudNotBetween(String value1, String value2) {
            addCriterion("id_solicitud not between", value1, value2, "idSolicitud");
            return (Criteria) this;
        }

        public Criteria andIdOcIsNull() {
            addCriterion("id_oc is null");
            return (Criteria) this;
        }

        public Criteria andIdOcIsNotNull() {
            addCriterion("id_oc is not null");
            return (Criteria) this;
        }

        public Criteria andIdOcEqualTo(String value) {
            addCriterion("id_oc =", value, "idOc");
            return (Criteria) this;
        }

        public Criteria andIdOcNotEqualTo(String value) {
            addCriterion("id_oc <>", value, "idOc");
            return (Criteria) this;
        }

        public Criteria andIdOcGreaterThan(String value) {
            addCriterion("id_oc >", value, "idOc");
            return (Criteria) this;
        }

        public Criteria andIdOcGreaterThanOrEqualTo(String value) {
            addCriterion("id_oc >=", value, "idOc");
            return (Criteria) this;
        }

        public Criteria andIdOcLessThan(String value) {
            addCriterion("id_oc <", value, "idOc");
            return (Criteria) this;
        }

        public Criteria andIdOcLessThanOrEqualTo(String value) {
            addCriterion("id_oc <=", value, "idOc");
            return (Criteria) this;
        }

        public Criteria andIdOcLike(String value) {
            addCriterion("id_oc like", value, "idOc");
            return (Criteria) this;
        }

        public Criteria andIdOcNotLike(String value) {
            addCriterion("id_oc not like", value, "idOc");
            return (Criteria) this;
        }

        public Criteria andIdOcIn(List<String> values) {
            addCriterion("id_oc in", values, "idOc");
            return (Criteria) this;
        }

        public Criteria andIdOcNotIn(List<String> values) {
            addCriterion("id_oc not in", values, "idOc");
            return (Criteria) this;
        }

        public Criteria andIdOcBetween(String value1, String value2) {
            addCriterion("id_oc between", value1, value2, "idOc");
            return (Criteria) this;
        }

        public Criteria andIdOcNotBetween(String value1, String value2) {
            addCriterion("id_oc not between", value1, value2, "idOc");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioIsNull() {
            addCriterion("id_usuario is null");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioIsNotNull() {
            addCriterion("id_usuario is not null");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioEqualTo(String value) {
            addCriterion("id_usuario =", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioNotEqualTo(String value) {
            addCriterion("id_usuario <>", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioGreaterThan(String value) {
            addCriterion("id_usuario >", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioGreaterThanOrEqualTo(String value) {
            addCriterion("id_usuario >=", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioLessThan(String value) {
            addCriterion("id_usuario <", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioLessThanOrEqualTo(String value) {
            addCriterion("id_usuario <=", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioLike(String value) {
            addCriterion("id_usuario like", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioNotLike(String value) {
            addCriterion("id_usuario not like", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioIn(List<String> values) {
            addCriterion("id_usuario in", values, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioNotIn(List<String> values) {
            addCriterion("id_usuario not in", values, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioBetween(String value1, String value2) {
            addCriterion("id_usuario between", value1, value2, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioNotBetween(String value1, String value2) {
            addCriterion("id_usuario not between", value1, value2, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdActividadIsNull() {
            addCriterion("id_actividad is null");
            return (Criteria) this;
        }

        public Criteria andIdActividadIsNotNull() {
            addCriterion("id_actividad is not null");
            return (Criteria) this;
        }

        public Criteria andIdActividadEqualTo(String value) {
            addCriterion("id_actividad =", value, "idActividad");
            return (Criteria) this;
        }

        public Criteria andIdActividadNotEqualTo(String value) {
            addCriterion("id_actividad <>", value, "idActividad");
            return (Criteria) this;
        }

        public Criteria andIdActividadGreaterThan(String value) {
            addCriterion("id_actividad >", value, "idActividad");
            return (Criteria) this;
        }

        public Criteria andIdActividadGreaterThanOrEqualTo(String value) {
            addCriterion("id_actividad >=", value, "idActividad");
            return (Criteria) this;
        }

        public Criteria andIdActividadLessThan(String value) {
            addCriterion("id_actividad <", value, "idActividad");
            return (Criteria) this;
        }

        public Criteria andIdActividadLessThanOrEqualTo(String value) {
            addCriterion("id_actividad <=", value, "idActividad");
            return (Criteria) this;
        }

        public Criteria andIdActividadLike(String value) {
            addCriterion("id_actividad like", value, "idActividad");
            return (Criteria) this;
        }

        public Criteria andIdActividadNotLike(String value) {
            addCriterion("id_actividad not like", value, "idActividad");
            return (Criteria) this;
        }

        public Criteria andIdActividadIn(List<String> values) {
            addCriterion("id_actividad in", values, "idActividad");
            return (Criteria) this;
        }

        public Criteria andIdActividadNotIn(List<String> values) {
            addCriterion("id_actividad not in", values, "idActividad");
            return (Criteria) this;
        }

        public Criteria andIdActividadBetween(String value1, String value2) {
            addCriterion("id_actividad between", value1, value2, "idActividad");
            return (Criteria) this;
        }

        public Criteria andIdActividadNotBetween(String value1, String value2) {
            addCriterion("id_actividad not between", value1, value2, "idActividad");
            return (Criteria) this;
        }

        public Criteria andIdStatusIsNull() {
            addCriterion("id_status is null");
            return (Criteria) this;
        }

        public Criteria andIdStatusIsNotNull() {
            addCriterion("id_status is not null");
            return (Criteria) this;
        }

        public Criteria andIdStatusEqualTo(Integer value) {
            addCriterion("id_status =", value, "idStatus");
            return (Criteria) this;
        }

        public Criteria andIdStatusNotEqualTo(Integer value) {
            addCriterion("id_status <>", value, "idStatus");
            return (Criteria) this;
        }

        public Criteria andIdStatusGreaterThan(Integer value) {
            addCriterion("id_status >", value, "idStatus");
            return (Criteria) this;
        }

        public Criteria andIdStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_status >=", value, "idStatus");
            return (Criteria) this;
        }

        public Criteria andIdStatusLessThan(Integer value) {
            addCriterion("id_status <", value, "idStatus");
            return (Criteria) this;
        }

        public Criteria andIdStatusLessThanOrEqualTo(Integer value) {
            addCriterion("id_status <=", value, "idStatus");
            return (Criteria) this;
        }

        public Criteria andIdStatusIn(List<Integer> values) {
            addCriterion("id_status in", values, "idStatus");
            return (Criteria) this;
        }

        public Criteria andIdStatusNotIn(List<Integer> values) {
            addCriterion("id_status not in", values, "idStatus");
            return (Criteria) this;
        }

        public Criteria andIdStatusBetween(Integer value1, Integer value2) {
            addCriterion("id_status between", value1, value2, "idStatus");
            return (Criteria) this;
        }

        public Criteria andIdStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("id_status not between", value1, value2, "idStatus");
            return (Criteria) this;
        }

        public Criteria andFechaIngresoActividadIsNull() {
            addCriterion("fecha_ingreso_actividad is null");
            return (Criteria) this;
        }

        public Criteria andFechaIngresoActividadIsNotNull() {
            addCriterion("fecha_ingreso_actividad is not null");
            return (Criteria) this;
        }

        public Criteria andFechaIngresoActividadEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_ingreso_actividad =", value, "fechaIngresoActividad");
            return (Criteria) this;
        }

        public Criteria andFechaIngresoActividadNotEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_ingreso_actividad <>", value, "fechaIngresoActividad");
            return (Criteria) this;
        }

        public Criteria andFechaIngresoActividadGreaterThan(Date value) {
            addCriterionForJDBCDate("fecha_ingreso_actividad >", value, "fechaIngresoActividad");
            return (Criteria) this;
        }

        public Criteria andFechaIngresoActividadGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_ingreso_actividad >=", value, "fechaIngresoActividad");
            return (Criteria) this;
        }

        public Criteria andFechaIngresoActividadLessThan(Date value) {
            addCriterionForJDBCDate("fecha_ingreso_actividad <", value, "fechaIngresoActividad");
            return (Criteria) this;
        }

        public Criteria andFechaIngresoActividadLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_ingreso_actividad <=", value, "fechaIngresoActividad");
            return (Criteria) this;
        }

        public Criteria andFechaIngresoActividadIn(List<Date> values) {
            addCriterionForJDBCDate("fecha_ingreso_actividad in", values, "fechaIngresoActividad");
            return (Criteria) this;
        }

        public Criteria andFechaIngresoActividadNotIn(List<Date> values) {
            addCriterionForJDBCDate("fecha_ingreso_actividad not in", values, "fechaIngresoActividad");
            return (Criteria) this;
        }

        public Criteria andFechaIngresoActividadBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fecha_ingreso_actividad between", value1, value2, "fechaIngresoActividad");
            return (Criteria) this;
        }

        public Criteria andFechaIngresoActividadNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fecha_ingreso_actividad not between", value1, value2, "fechaIngresoActividad");
            return (Criteria) this;
        }

        public Criteria andTiempoIngresoActividadIsNull() {
            addCriterion("tiempo_ingreso_actividad is null");
            return (Criteria) this;
        }

        public Criteria andTiempoIngresoActividadIsNotNull() {
            addCriterion("tiempo_ingreso_actividad is not null");
            return (Criteria) this;
        }

        public Criteria andTiempoIngresoActividadEqualTo(Long value) {
            addCriterion("tiempo_ingreso_actividad =", value, "tiempoIngresoActividad");
            return (Criteria) this;
        }

        public Criteria andTiempoIngresoActividadNotEqualTo(Long value) {
            addCriterion("tiempo_ingreso_actividad <>", value, "tiempoIngresoActividad");
            return (Criteria) this;
        }

        public Criteria andTiempoIngresoActividadGreaterThan(Long value) {
            addCriterion("tiempo_ingreso_actividad >", value, "tiempoIngresoActividad");
            return (Criteria) this;
        }

        public Criteria andTiempoIngresoActividadGreaterThanOrEqualTo(Long value) {
            addCriterion("tiempo_ingreso_actividad >=", value, "tiempoIngresoActividad");
            return (Criteria) this;
        }

        public Criteria andTiempoIngresoActividadLessThan(Long value) {
            addCriterion("tiempo_ingreso_actividad <", value, "tiempoIngresoActividad");
            return (Criteria) this;
        }

        public Criteria andTiempoIngresoActividadLessThanOrEqualTo(Long value) {
            addCriterion("tiempo_ingreso_actividad <=", value, "tiempoIngresoActividad");
            return (Criteria) this;
        }

        public Criteria andTiempoIngresoActividadIn(List<Long> values) {
            addCriterion("tiempo_ingreso_actividad in", values, "tiempoIngresoActividad");
            return (Criteria) this;
        }

        public Criteria andTiempoIngresoActividadNotIn(List<Long> values) {
            addCriterion("tiempo_ingreso_actividad not in", values, "tiempoIngresoActividad");
            return (Criteria) this;
        }

        public Criteria andTiempoIngresoActividadBetween(Long value1, Long value2) {
            addCriterion("tiempo_ingreso_actividad between", value1, value2, "tiempoIngresoActividad");
            return (Criteria) this;
        }

        public Criteria andTiempoIngresoActividadNotBetween(Long value1, Long value2) {
            addCriterion("tiempo_ingreso_actividad not between", value1, value2, "tiempoIngresoActividad");
            return (Criteria) this;
        }

        public Criteria andFechaLecturaActividadIsNull() {
            addCriterion("fecha_lectura_actividad is null");
            return (Criteria) this;
        }

        public Criteria andFechaLecturaActividadIsNotNull() {
            addCriterion("fecha_lectura_actividad is not null");
            return (Criteria) this;
        }

        public Criteria andFechaLecturaActividadEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_lectura_actividad =", value, "fechaLecturaActividad");
            return (Criteria) this;
        }

        public Criteria andFechaLecturaActividadNotEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_lectura_actividad <>", value, "fechaLecturaActividad");
            return (Criteria) this;
        }

        public Criteria andFechaLecturaActividadGreaterThan(Date value) {
            addCriterionForJDBCDate("fecha_lectura_actividad >", value, "fechaLecturaActividad");
            return (Criteria) this;
        }

        public Criteria andFechaLecturaActividadGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_lectura_actividad >=", value, "fechaLecturaActividad");
            return (Criteria) this;
        }

        public Criteria andFechaLecturaActividadLessThan(Date value) {
            addCriterionForJDBCDate("fecha_lectura_actividad <", value, "fechaLecturaActividad");
            return (Criteria) this;
        }

        public Criteria andFechaLecturaActividadLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_lectura_actividad <=", value, "fechaLecturaActividad");
            return (Criteria) this;
        }

        public Criteria andFechaLecturaActividadIn(List<Date> values) {
            addCriterionForJDBCDate("fecha_lectura_actividad in", values, "fechaLecturaActividad");
            return (Criteria) this;
        }

        public Criteria andFechaLecturaActividadNotIn(List<Date> values) {
            addCriterionForJDBCDate("fecha_lectura_actividad not in", values, "fechaLecturaActividad");
            return (Criteria) this;
        }

        public Criteria andFechaLecturaActividadBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fecha_lectura_actividad between", value1, value2, "fechaLecturaActividad");
            return (Criteria) this;
        }

        public Criteria andFechaLecturaActividadNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fecha_lectura_actividad not between", value1, value2, "fechaLecturaActividad");
            return (Criteria) this;
        }

        public Criteria andTiempoLecturaActividadIsNull() {
            addCriterion("tiempo_lectura_actividad is null");
            return (Criteria) this;
        }

        public Criteria andTiempoLecturaActividadIsNotNull() {
            addCriterion("tiempo_lectura_actividad is not null");
            return (Criteria) this;
        }

        public Criteria andTiempoLecturaActividadEqualTo(Long value) {
            addCriterion("tiempo_lectura_actividad =", value, "tiempoLecturaActividad");
            return (Criteria) this;
        }

        public Criteria andTiempoLecturaActividadNotEqualTo(Long value) {
            addCriterion("tiempo_lectura_actividad <>", value, "tiempoLecturaActividad");
            return (Criteria) this;
        }

        public Criteria andTiempoLecturaActividadGreaterThan(Long value) {
            addCriterion("tiempo_lectura_actividad >", value, "tiempoLecturaActividad");
            return (Criteria) this;
        }

        public Criteria andTiempoLecturaActividadGreaterThanOrEqualTo(Long value) {
            addCriterion("tiempo_lectura_actividad >=", value, "tiempoLecturaActividad");
            return (Criteria) this;
        }

        public Criteria andTiempoLecturaActividadLessThan(Long value) {
            addCriterion("tiempo_lectura_actividad <", value, "tiempoLecturaActividad");
            return (Criteria) this;
        }

        public Criteria andTiempoLecturaActividadLessThanOrEqualTo(Long value) {
            addCriterion("tiempo_lectura_actividad <=", value, "tiempoLecturaActividad");
            return (Criteria) this;
        }

        public Criteria andTiempoLecturaActividadIn(List<Long> values) {
            addCriterion("tiempo_lectura_actividad in", values, "tiempoLecturaActividad");
            return (Criteria) this;
        }

        public Criteria andTiempoLecturaActividadNotIn(List<Long> values) {
            addCriterion("tiempo_lectura_actividad not in", values, "tiempoLecturaActividad");
            return (Criteria) this;
        }

        public Criteria andTiempoLecturaActividadBetween(Long value1, Long value2) {
            addCriterion("tiempo_lectura_actividad between", value1, value2, "tiempoLecturaActividad");
            return (Criteria) this;
        }

        public Criteria andTiempoLecturaActividadNotBetween(Long value1, Long value2) {
            addCriterion("tiempo_lectura_actividad not between", value1, value2, "tiempoLecturaActividad");
            return (Criteria) this;
        }

        public Criteria andFechaCompletadoActividadIsNull() {
            addCriterion("fecha_completado_actividad is null");
            return (Criteria) this;
        }

        public Criteria andFechaCompletadoActividadIsNotNull() {
            addCriterion("fecha_completado_actividad is not null");
            return (Criteria) this;
        }

        public Criteria andFechaCompletadoActividadEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_completado_actividad =", value, "fechaCompletadoActividad");
            return (Criteria) this;
        }

        public Criteria andFechaCompletadoActividadNotEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_completado_actividad <>", value, "fechaCompletadoActividad");
            return (Criteria) this;
        }

        public Criteria andFechaCompletadoActividadGreaterThan(Date value) {
            addCriterionForJDBCDate("fecha_completado_actividad >", value, "fechaCompletadoActividad");
            return (Criteria) this;
        }

        public Criteria andFechaCompletadoActividadGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_completado_actividad >=", value, "fechaCompletadoActividad");
            return (Criteria) this;
        }

        public Criteria andFechaCompletadoActividadLessThan(Date value) {
            addCriterionForJDBCDate("fecha_completado_actividad <", value, "fechaCompletadoActividad");
            return (Criteria) this;
        }

        public Criteria andFechaCompletadoActividadLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_completado_actividad <=", value, "fechaCompletadoActividad");
            return (Criteria) this;
        }

        public Criteria andFechaCompletadoActividadIn(List<Date> values) {
            addCriterionForJDBCDate("fecha_completado_actividad in", values, "fechaCompletadoActividad");
            return (Criteria) this;
        }

        public Criteria andFechaCompletadoActividadNotIn(List<Date> values) {
            addCriterionForJDBCDate("fecha_completado_actividad not in", values, "fechaCompletadoActividad");
            return (Criteria) this;
        }

        public Criteria andFechaCompletadoActividadBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fecha_completado_actividad between", value1, value2, "fechaCompletadoActividad");
            return (Criteria) this;
        }

        public Criteria andFechaCompletadoActividadNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fecha_completado_actividad not between", value1, value2, "fechaCompletadoActividad");
            return (Criteria) this;
        }

        public Criteria andTiempoCompletadoActividadIsNull() {
            addCriterion("tiempo_completado_actividad is null");
            return (Criteria) this;
        }

        public Criteria andTiempoCompletadoActividadIsNotNull() {
            addCriterion("tiempo_completado_actividad is not null");
            return (Criteria) this;
        }

        public Criteria andTiempoCompletadoActividadEqualTo(Long value) {
            addCriterion("tiempo_completado_actividad =", value, "tiempoCompletadoActividad");
            return (Criteria) this;
        }

        public Criteria andTiempoCompletadoActividadNotEqualTo(Long value) {
            addCriterion("tiempo_completado_actividad <>", value, "tiempoCompletadoActividad");
            return (Criteria) this;
        }

        public Criteria andTiempoCompletadoActividadGreaterThan(Long value) {
            addCriterion("tiempo_completado_actividad >", value, "tiempoCompletadoActividad");
            return (Criteria) this;
        }

        public Criteria andTiempoCompletadoActividadGreaterThanOrEqualTo(Long value) {
            addCriterion("tiempo_completado_actividad >=", value, "tiempoCompletadoActividad");
            return (Criteria) this;
        }

        public Criteria andTiempoCompletadoActividadLessThan(Long value) {
            addCriterion("tiempo_completado_actividad <", value, "tiempoCompletadoActividad");
            return (Criteria) this;
        }

        public Criteria andTiempoCompletadoActividadLessThanOrEqualTo(Long value) {
            addCriterion("tiempo_completado_actividad <=", value, "tiempoCompletadoActividad");
            return (Criteria) this;
        }

        public Criteria andTiempoCompletadoActividadIn(List<Long> values) {
            addCriterion("tiempo_completado_actividad in", values, "tiempoCompletadoActividad");
            return (Criteria) this;
        }

        public Criteria andTiempoCompletadoActividadNotIn(List<Long> values) {
            addCriterion("tiempo_completado_actividad not in", values, "tiempoCompletadoActividad");
            return (Criteria) this;
        }

        public Criteria andTiempoCompletadoActividadBetween(Long value1, Long value2) {
            addCriterion("tiempo_completado_actividad between", value1, value2, "tiempoCompletadoActividad");
            return (Criteria) this;
        }

        public Criteria andTiempoCompletadoActividadNotBetween(Long value1, Long value2) {
            addCriterion("tiempo_completado_actividad not between", value1, value2, "tiempoCompletadoActividad");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bpm_instancia_historica
     *
     * @mbg.generated do_not_delete_during_merge Tue Jul 10 14:37:04 EDT 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bpm_instancia_historica
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}