package cl.valpoSystems.bpmTraking.orm.model;

import java.util.Date;

public class BpmInstanciaHistorica {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bpm_instancia_historica.idreg
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    private Long idreg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bpm_instancia_historica.id_instancia
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    private String idInstancia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bpm_instancia_historica.id_proceso
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    private String idProceso;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bpm_instancia_historica.id_solicitud
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    private String idSolicitud;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bpm_instancia_historica.id_oc
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    private String idOc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bpm_instancia_historica.id_usuario
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    private String idUsuario;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bpm_instancia_historica.id_actividad
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    private String idActividad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bpm_instancia_historica.id_status
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    private Integer idStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bpm_instancia_historica.fecha_ingreso_actividad
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    private Date fechaIngresoActividad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bpm_instancia_historica.tiempo_ingreso_actividad
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    private Long tiempoIngresoActividad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bpm_instancia_historica.fecha_lectura_actividad
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    private Date fechaLecturaActividad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bpm_instancia_historica.tiempo_lectura_actividad
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    private Long tiempoLecturaActividad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bpm_instancia_historica.fecha_completado_actividad
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    private Date fechaCompletadoActividad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bpm_instancia_historica.tiempo_completado_actividad
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    private Long tiempoCompletadoActividad;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bpm_instancia_historica.idreg
     *
     * @return the value of bpm_instancia_historica.idreg
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public Long getIdreg() {
        return idreg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bpm_instancia_historica.idreg
     *
     * @param idreg the value for bpm_instancia_historica.idreg
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public void setIdreg(Long idreg) {
        this.idreg = idreg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bpm_instancia_historica.id_instancia
     *
     * @return the value of bpm_instancia_historica.id_instancia
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public String getIdInstancia() {
        return idInstancia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bpm_instancia_historica.id_instancia
     *
     * @param idInstancia the value for bpm_instancia_historica.id_instancia
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public void setIdInstancia(String idInstancia) {
        this.idInstancia = idInstancia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bpm_instancia_historica.id_proceso
     *
     * @return the value of bpm_instancia_historica.id_proceso
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public String getIdProceso() {
        return idProceso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bpm_instancia_historica.id_proceso
     *
     * @param idProceso the value for bpm_instancia_historica.id_proceso
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public void setIdProceso(String idProceso) {
        this.idProceso = idProceso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bpm_instancia_historica.id_solicitud
     *
     * @return the value of bpm_instancia_historica.id_solicitud
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public String getIdSolicitud() {
        return idSolicitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bpm_instancia_historica.id_solicitud
     *
     * @param idSolicitud the value for bpm_instancia_historica.id_solicitud
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public void setIdSolicitud(String idSolicitud) {
        this.idSolicitud = idSolicitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bpm_instancia_historica.id_oc
     *
     * @return the value of bpm_instancia_historica.id_oc
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public String getIdOc() {
        return idOc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bpm_instancia_historica.id_oc
     *
     * @param idOc the value for bpm_instancia_historica.id_oc
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public void setIdOc(String idOc) {
        this.idOc = idOc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bpm_instancia_historica.id_usuario
     *
     * @return the value of bpm_instancia_historica.id_usuario
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public String getIdUsuario() {
        return idUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bpm_instancia_historica.id_usuario
     *
     * @param idUsuario the value for bpm_instancia_historica.id_usuario
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bpm_instancia_historica.id_actividad
     *
     * @return the value of bpm_instancia_historica.id_actividad
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public String getIdActividad() {
        return idActividad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bpm_instancia_historica.id_actividad
     *
     * @param idActividad the value for bpm_instancia_historica.id_actividad
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public void setIdActividad(String idActividad) {
        this.idActividad = idActividad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bpm_instancia_historica.id_status
     *
     * @return the value of bpm_instancia_historica.id_status
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public Integer getIdStatus() {
        return idStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bpm_instancia_historica.id_status
     *
     * @param idStatus the value for bpm_instancia_historica.id_status
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public void setIdStatus(Integer idStatus) {
        this.idStatus = idStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bpm_instancia_historica.fecha_ingreso_actividad
     *
     * @return the value of bpm_instancia_historica.fecha_ingreso_actividad
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public Date getFechaIngresoActividad() {
        return fechaIngresoActividad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bpm_instancia_historica.fecha_ingreso_actividad
     *
     * @param fechaIngresoActividad the value for bpm_instancia_historica.fecha_ingreso_actividad
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public void setFechaIngresoActividad(Date fechaIngresoActividad) {
        this.fechaIngresoActividad = fechaIngresoActividad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bpm_instancia_historica.tiempo_ingreso_actividad
     *
     * @return the value of bpm_instancia_historica.tiempo_ingreso_actividad
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public Long getTiempoIngresoActividad() {
        return tiempoIngresoActividad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bpm_instancia_historica.tiempo_ingreso_actividad
     *
     * @param tiempoIngresoActividad the value for bpm_instancia_historica.tiempo_ingreso_actividad
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public void setTiempoIngresoActividad(Long tiempoIngresoActividad) {
        this.tiempoIngresoActividad = tiempoIngresoActividad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bpm_instancia_historica.fecha_lectura_actividad
     *
     * @return the value of bpm_instancia_historica.fecha_lectura_actividad
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public Date getFechaLecturaActividad() {
        return fechaLecturaActividad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bpm_instancia_historica.fecha_lectura_actividad
     *
     * @param fechaLecturaActividad the value for bpm_instancia_historica.fecha_lectura_actividad
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public void setFechaLecturaActividad(Date fechaLecturaActividad) {
        this.fechaLecturaActividad = fechaLecturaActividad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bpm_instancia_historica.tiempo_lectura_actividad
     *
     * @return the value of bpm_instancia_historica.tiempo_lectura_actividad
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public Long getTiempoLecturaActividad() {
        return tiempoLecturaActividad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bpm_instancia_historica.tiempo_lectura_actividad
     *
     * @param tiempoLecturaActividad the value for bpm_instancia_historica.tiempo_lectura_actividad
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public void setTiempoLecturaActividad(Long tiempoLecturaActividad) {
        this.tiempoLecturaActividad = tiempoLecturaActividad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bpm_instancia_historica.fecha_completado_actividad
     *
     * @return the value of bpm_instancia_historica.fecha_completado_actividad
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public Date getFechaCompletadoActividad() {
        return fechaCompletadoActividad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bpm_instancia_historica.fecha_completado_actividad
     *
     * @param fechaCompletadoActividad the value for bpm_instancia_historica.fecha_completado_actividad
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public void setFechaCompletadoActividad(Date fechaCompletadoActividad) {
        this.fechaCompletadoActividad = fechaCompletadoActividad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bpm_instancia_historica.tiempo_completado_actividad
     *
     * @return the value of bpm_instancia_historica.tiempo_completado_actividad
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public Long getTiempoCompletadoActividad() {
        return tiempoCompletadoActividad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bpm_instancia_historica.tiempo_completado_actividad
     *
     * @param tiempoCompletadoActividad the value for bpm_instancia_historica.tiempo_completado_actividad
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    public void setTiempoCompletadoActividad(Long tiempoCompletadoActividad) {
        this.tiempoCompletadoActividad = tiempoCompletadoActividad;
    }
}