package cl.valpoSystems.bpmTraking.orm.client;

import cl.valpoSystems.bpmTraking.orm.model.BpmInstanciaHistorica;
import cl.valpoSystems.bpmTraking.orm.model.BpmInstanciaHistoricaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BpmInstanciaHistoricaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bpm_instancia_historica
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    long countByExample(BpmInstanciaHistoricaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bpm_instancia_historica
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    int deleteByExample(BpmInstanciaHistoricaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bpm_instancia_historica
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    int deleteByPrimaryKey(Long idreg);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bpm_instancia_historica
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    int insert(BpmInstanciaHistorica record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bpm_instancia_historica
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    int insertSelective(BpmInstanciaHistorica record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bpm_instancia_historica
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    List<BpmInstanciaHistorica> selectByExample(BpmInstanciaHistoricaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bpm_instancia_historica
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    BpmInstanciaHistorica selectByPrimaryKey(Long idreg);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bpm_instancia_historica
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    int updateByExampleSelective(@Param("record") BpmInstanciaHistorica record, @Param("example") BpmInstanciaHistoricaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bpm_instancia_historica
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    int updateByExample(@Param("record") BpmInstanciaHistorica record, @Param("example") BpmInstanciaHistoricaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bpm_instancia_historica
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    int updateByPrimaryKeySelective(BpmInstanciaHistorica record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bpm_instancia_historica
     *
     * @mbg.generated Tue Jul 10 14:37:04 EDT 2018
     */
    int updateByPrimaryKey(BpmInstanciaHistorica record);
}